### ISSUE TITLE
Roadmap

### ISSUE THREAD

**Issue by Deraen** [ngrunwald/ring-middleware-format#52]
- [ ] Separate middleware and formatters: https://github.com/metosin/ring-middleware-format/blob/refactor/src/ring/middleware/formatters.clj#L72-L95
- [ ] Async support (separate formatters should make this easier)
  - Aleph, Yada, Pedestal
- [ ] Make sure large requests are handled efficiently (not read into memory to check character encoding etc.)

**Comment by Deraen** [comment]
All this will be solved by https://github.com/metosin/muuntaja
